server {
    listen 3000;
    server_name _;
    charset utf-8;
    charset_types text/html text/css application/javascript application/json image/svg+xml;
    add_header Content-Language pt-BR always;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
