package com.pdv2cloud.model.entity;

public enum AlertType {
    LOW_STOCK,
    HIGH_PERFORMING,
    SLOW_MOVING,
    EXPIRATION_RISK,
    PROMOTION_OPPORTUNITY,
    DEMAND_SPIKE,
    MOMENTUM_REVERSAL,
    BASKET_OPPORTUNITY,
    ZERO_SALES,
    PRICE_ABOVE_MARKET,
    HEALTH_CRITICAL
}
